- name: Validate EE and collection
  hosts: localhost
  gather_facts: false
  tasks:
    - name: List installed collections
      ansible.builtin.command: ansible-galaxy collection list
      register: result

    - name: Show result
      ansible.builtin.debug:
        var: result.stdout_lines
