---
- name: Test de conectividad con VMware VCD
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_hostname: "{{ vcenter_hostname | default('https://vcd-lab.clarocloud.com') }}"
    vcenter_username: "{{ vcenter_username | default('usuario@system') }}"
    vcenter_password: "{{ vcenter_password | default('SuperSecreta') }}"
    vcenter_org: "{{ vcenter_org | default('system') }}"
    vcenter_verify_ssl: false

  tasks:
    - name: Probar resolución DNS hacia VCD
      ansible.builtin.getent:
        database: hosts
        key: "{{ vcenter_hostname | regex_replace('^https?://', '') }}"
      register: dns_check
      ignore_errors: true

    - name: Mostrar resultado DNS
      debug:
        var: dns_check.ansible_facts.getent_hosts

    - name: Probar conexión HTTPS hacia VCD (sin validar certificado)
      ansible.builtin.uri:
        url: "{{ vcenter_hostname }}/api/sessions"
        method: GET
        validate_certs: no
        return_content: no
      register: http_check
      ignore_errors: true

    - name: Mostrar resultado HTTPS
      debug:
        var: http_check.status

    - name: Conectar al VCD y obtener información de la organización
      community.vmware.vmware_vcd_org_info:
        hostname: "{{ vcenter_hostname | regex_replace('^https?://', '') }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        org: "{{ vcenter_org }}"
        verify_ssl_certs: "{{ vcenter_verify_ssl }}"
      register: vcd_info
      ignore_errors: true

    - name: Mostrar info de la organización en VCD
      debug:
        var: vcd_info
