---
- name: VMware Cloud Director Onboarding - AWX Orchestration
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # ⚙️ Variables de conexión al VCD — inyectadas desde credenciales de AWX
    vcd_hostname: "{{ lookup('env', 'VCD_HOST') }}"
    vcd_org: "{{ lookup('env', 'VCD_ORG') }}"
    vcd_user: "{{ lookup('env', 'VCD_USER') }}"
    vcd_password: "{{ lookup('env', 'VCD_PASSWORD') }}"
    vcd_verify_ssl_certs: "{{ lookup('env', 'VCD_VERIFY_SSL_CERTS') | default(false) }}"
    vcd_api_version: "{{ lookup('env', 'VCD_API_VERSION') | default('39.1') }}"
    vcd_apikey: "{{ lookup('env', 'VCD_TOKEN') }}" # Asegúrate de tener este valor en credenciales

    # 📦 Datos dinámicos — enviados desde survey o extra_vars
    orgFullName: "{{ orgFullName }}"
    orgVdcName: "{{ orgVdcName }}"
    cpuQuota: "{{ cpuQuota }}"
    memoryQuota: "{{ memoryQuota }}"
    storageQuota: "{{ storageQuota }}"
    mail: "{{ mail }}"
    firstName: "{{ firstName }}"
    lastName: "{{ lastName }}"
    networkType: "{{ networkType }}"
    trial: "{{ trial | default(false) }}"

  tasks:
    # =======================================
    # Autenticación directa a VCD (sin pyvcloud)
    # =======================================
    - name: Obtener token OAuth desde VCD
      ansible.builtin.uri:
        url: "{{ vcd_hostname }}/oauth/provider/token"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body: "grant_type=refresh_token&refresh_token={{ vcd_apikey }}"
        body_format: form-urlencoded
        return_content: yes
        validate_certs: false
      register: vcd_auth_response

    - name: Guardar token JWT
      ansible.builtin.set_fact:
        vcd_access_token: "{{ vcd_auth_response.json.access_token }}"

    - name: Mostrar token temporal (debug)
      ansible.builtin.debug:
        msg: "Token JWT generado: {{ vcd_access_token | default('NO DEFINIDO') }}"

    - name: Validar autenticación exitosa
      ansible.builtin.debug:
        msg: "✅ Token obtenido correctamente para VCD: {{ vcd_access_token[:20] }}..."

    # =======================================
    # Ejecución de roles (ya con token disponible)
    # =======================================
    - name: Ejecutar roles de onboarding
      include_role:
        name: "{{ item }}"
      vars:
        vcd_hostname: "{{ vcd_hostname }}"
        vcd_org: "{{ vcd_org }}"
        vcd_user: "{{ vcd_user }}"
        vcd_password: "{{ vcd_password }}"
        vcd_verify_ssl_certs: "{{ vcd_verify_ssl_certs }}"
        vcd_api_version: "{{ vcd_api_version }}"
        vcd_apikey: "{{ vcd_apikey }}"
        vcd_access_token: "{{ vcd_access_token }}"
        orgFullName: "{{ orgFullName }}"
        orgVdcName: "{{ orgVdcName }}"
        cpuQuota: "{{ cpuQuota }}"
        memoryQuota: "{{ memoryQuota }}"
        storageQuota: "{{ storageQuota }}"
        mail: "{{ mail }}"
        firstName: "{{ firstName }}"
        lastName: "{{ lastName }}"
        networkType: "{{ networkType }}"
        trial: "{{ trial | default(false) }}"

      loop:
        - organization
        - orgvcd
        - network
