---
vCpuInMhz: 1000
networkQuota: 10
isThinProvision: true
usesFastProvisioning: true
allocationModel: "ReservationPool"
storageProfile: "Standard"
providerVdc: "ProviderVDC-Default"
networkPool: "Default-NetworkPool"
